import type { Post, UserProfile } from './types'

export const initialProfile: UserProfile = {
  name: 'Andrew',
  handle: 'andrew',
  pronouns: 'he / him',
  bio: 'I build small tools, write about the web, and take the long way home.',
  location: 'Kuala Lumpur, MY',
  website: 'andrew.builds',
  interests: ['web tools', 'small internet', 'field notes', 'coffee'],
  following: 184,
  followers: 2470,
  posts: 68,
}

export const initialPosts: Post[] = [
  {
    id: 'post-1',
    author: 'Andrew',
    handle: 'andrew',
    avatar: 'AN',
    published: 'Today, 8:14 AM',
    title: 'What survives a prototype',
    excerpt:
      'A prototype can be loud and wrong. I keep the sentence that names who needs the thing and what decision it should make easier.',
    body:
      'I let prototypes be loud, awkward, and wrong. Their job is to show me where the idea breaks.\n\nWhen I throw one away, I keep one sentence: who needs this, what pressure are they under, and which decision should get easier? That sentence usually outlives the screen.',
    tags: ['design practice', 'notes'],
    readTime: 2,
    accent: '#c9e4d7',
    artwork: 'grid',
    saved: true,
    liked: true,
    likes: 84,
    comments: 12,
  },
  {
    id: 'post-2',
    author: 'Rowan Ellis',
    handle: 'rowanbuilds',
    avatar: 'RE',
    published: 'Yesterday, 4:32 PM',
    title: 'Leave the seam visible',
    excerpt:
      'When two systems hand work to each other, a label and a loading state do more for trust than a polished animation.',
    body:
      'When two systems hand work to each other, I want the page to say so. A small label, a clear loading state, and a way to cancel are enough most of the time. People do not need a magic trick. They need to know whether the button worked.',
    tags: ['web craft', 'agents'],
    readTime: 2,
    accent: '#f0d5a9',
    artwork: 'signal',
    saved: false,
    liked: false,
    likes: 61,
    comments: 8,
  },
  {
    id: 'post-3',
    author: 'Nia Okafor',
    handle: 'niawrites',
    avatar: 'NO',
    published: 'Monday, 11:06 AM',
    title: 'Defaults I can undo',
    excerpt:
      'Remember my reading width and last filter, then give me a clear way back when the guess misses.',
    body:
      'Remember my reading width and last filter. Keep the quiet setting quiet. Then leave a clear way back when the guess misses. I trust a preference more when I can see where to change it.',
    tags: ['personal tech', 'field notes'],
    readTime: 1,
    accent: '#d7dba7',
    artwork: 'orbit',
    saved: true,
    liked: false,
    likes: 105,
    comments: 17,
  },
  {
    id: 'post-4',
    author: 'Theo Park',
    handle: 'theopark',
    avatar: 'TP',
    published: 'Sunday, 9:20 PM',
    title: 'A feed with an end',
    excerpt:
      'I would rather have a few things I can return to than an endless list that forgets what I saved.',
    body:
      'I would rather have a few things I can return to than an endless list. Give me enough context to remember why I saved something. Then let the feed end so I can close the tab without feeling behind.',
    tags: ['slow social', 'web culture'],
    readTime: 2,
    accent: '#edc6bc',
    artwork: 'paper',
    saved: false,
    liked: false,
    likes: 42,
    comments: 4,
  },
]

export const additionalSamplePosts: Post[] = [
  {
    id: 'post-5',
    author: 'Andrew',
    handle: 'andrew',
    avatar: 'AN',
    published: 'Saturday, 10:12 AM',
    title: 'The tab I keep open',
    excerpt: 'I leave one blank tab beside my work. It is where I put the sentence I do not want to lose.',
    body: 'I leave one blank tab beside my work. It is where I put the sentence I do not want to lose.\n\nToday it says: "Make the next choice easier." That is enough for now.',
    tags: ['small tools', 'work notes'],
    readTime: 1,
    accent: '#c9e4d7',
    artwork: 'grid',
    saved: true,
    liked: false,
    likes: 28,
    comments: 3,
  },
  {
    id: 'post-6',
    author: 'Leah Park',
    handle: 'leahmakes',
    avatar: 'LP',
    published: 'Friday, 2:05 PM',
    title: 'A button that waits',
    excerpt: 'The best button on my phone is the one that does not hurry me into the next screen.',
    body: 'The best button on my phone is the one that does not hurry me. I press it, the page changes, and I still know where I am.',
    tags: ['interface notes', 'mobile'],
    readTime: 1,
    accent: '#f0d5a9',
    artwork: 'signal',
    saved: false,
    liked: false,
    likes: 34,
    comments: 5,
  },
  {
    id: 'post-7',
    author: 'Andrew',
    handle: 'andrew',
    avatar: 'AN',
    published: 'Thursday, 8:47 AM',
    title: 'A feed should know when to stop',
    excerpt: 'I do not need another endless list. I need a place that remembers what I meant to come back to.',
    body: 'I used to think a good feed had to keep going. If there was more below the fold, the product was doing its job. Then I noticed what happened at the end of a long scroll. I could not remember why I opened the app.\n\nNow I want a feed to stop on purpose. Give me a handful of posts, a clear saved list, and a small sign that I have reached the end. The limit makes each item easier to see.\n\nThis changes the work for the person who builds the feed. Ranking cannot do all the talking. The page has to say what it knows, what it picked, and what the user can change.\n\nA stop also leaves room for a return. I can close the tab and come back without feeling behind. That is a better promise than "there is always more."\n\nI am still figuring out the right number. Some days it is four posts. On a busy day it is one. The useful part is the decision to stop treating attention as an infinite resource.',
    tags: ['slow social', 'product notes'],
    readTime: 5,
    accent: '#d7dba7',
    artwork: 'orbit',
    saved: false,
    liked: true,
    likes: 77,
    comments: 11,
  },
  {
    id: 'post-8',
    author: 'Rowan Ellis',
    handle: 'rowanbuilds',
    avatar: 'RE',
    published: 'Wednesday, 6:18 PM',
    title: 'What a loading label gave back',
    excerpt: 'A small loading sentence made a slow handoff easier to trust. People stopped clicking the button twice.',
    body: 'I once replaced a spinning circle with three words: "Checking your notes." The request still took the same amount of time. People stopped clicking the button twice.\n\nThat small label answered the question the spinner left open. The app had heard me. It was waiting on another system. I did not need to watch the animation and guess.\n\nThere is a temptation to hide slow work because the delay feels like a flaw. I think the opposite is true. Name the wait. Give it a cancel button when you can. Let the person decide whether the result is worth another ten seconds.\n\nThe label also made bugs easier to spot. When the wrong step appeared, we could see where the handoff broke. Clear words helped us debug the product, not only explain it.',
    tags: ['web craft', 'agents'],
    readTime: 4,
    accent: '#edc6bc',
    artwork: 'paper',
    saved: true,
    liked: false,
    likes: 53,
    comments: 7,
  },
  {
    id: 'post-9',
    author: 'Nia Okafor',
    handle: 'niawrites',
    avatar: 'NO',
    published: 'Tuesday, 9:03 AM',
    title: 'The notes I write before I build',
    excerpt: 'Before I open the editor, I write down the person, the pressure, and the choice I want to make easier.',
    body: 'Before I open the editor, I write three lines in a paper notebook.\n\nWho is here? What are they trying to finish? What choice keeps getting delayed?\n\nThe answers are usually less tidy than the brief. A person may want to compare two things, but what they need is permission to stop researching. Someone may ask for a dashboard when they really want to know whether the work is safe to ship. The sentence changes when I sit with it for a minute.\n\nI keep these notes beside the keyboard while I build. They stop me from adding a second control when the first one is unclear. They also give me something to test. If the screen cannot help with the choice I wrote down, the screen is not ready.\n\nI used to treat the notebook as warm-up work. Now I think it is where the product starts. The code comes after I know what I am asking it to do.\n\nThe method is small enough to skip. That is why I keep it visible.',
    tags: ['field notes', 'design practice'],
    readTime: 5,
    accent: '#c9e4d7',
    artwork: 'sun',
    saved: false,
    liked: false,
    likes: 91,
    comments: 14,
  },
  {
    id: 'post-10',
    author: 'Sofia Bell',
    handle: 'sofiabell',
    avatar: 'SB',
    published: 'Monday, 7:26 PM',
    title: 'A slower inbox',
    excerpt: 'I turned off every badge for a week. I missed less than I expected.',
    body: 'I turned off every badge for a week. I missed less than I expected.\n\nThe messages were still there. I just chose when to look. My inbox felt less like a room asking for attention and more like a drawer I could open.',
    tags: ['slow media', 'small rituals'],
    readTime: 1,
    accent: '#f0d5a9',
    artwork: 'signal',
    saved: false,
    liked: false,
    likes: 39,
    comments: 6,
  },
]

export const suggestedProfiles = [
  { name: 'Leah Park', handle: 'leahmakes', avatar: 'LP', note: 'micro-interactions' },
  { name: 'Arun Raman', handle: 'arunraman', avatar: 'AR', note: 'the small web' },
  { name: 'Sofia Bell', handle: 'sofiabell', avatar: 'SB', note: 'field recordings' },
]
